#!/bin/sh
# Make the generated Xcode project build the exact dependency revisions
# recorded in MacDownKit's committed Package.resolved (#148 LC-05).
#
# The .xcodeproj is generated by XcodeGen and git-ignored, so its workspace
# Package.resolved cannot be committed. The app's only package reference is
# the local MacDownKit package, whose remote dependencies are the whole
# graph, so MacDownKit's lock file is also the correct workspace lock file.
#
# Run after `xcodegen generate`, then pass
# `-onlyUsePackageVersionsFromResolvedFile` to xcodebuild. Without this copy,
# xcodebuild silently re-resolves (SwiftTreeSitter tracks a moving branch)
# even when that flag is set.
#
# `--check` instead verifies that the workspace copy still exists and matches
# the committed file, so CI fails if a build rewrote or removed it.
set -eu

cd "$(dirname "$0")/.."
source_file=Packages/MacDownKit/Package.resolved
workspace_file=MacDown2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

if [ "${1:-}" = "--check" ]; then
    if ! cmp -s "$source_file" "$workspace_file"; then
        echo "error: $workspace_file is missing or differs from $source_file" >&2
        exit 1
    fi
    echo "Xcode package versions match $source_file"
    exit 0
fi

if [ ! -d MacDown2.xcodeproj ]; then
    echo "error: MacDown2.xcodeproj not found; run 'xcodegen generate' first" >&2
    exit 1
fi
mkdir -p "$(dirname "$workspace_file")"
cp "$source_file" "$workspace_file"
echo "Pinned Xcode package versions to $source_file"
